### ISSUE TITLE
Requirement to PHP 5.6?

### ISSUE THREAD

**Issue by mario-naether** [jacekk/codeception-dataprovider-module#3]
Hi,

this module has a requirement to PHP >=5.6.
Is this req realy needed for you module or can you remove this, for using your module in installations with PHP 5.4 ?

**Comment by jacekk** [comment]
@mario-naether 
https://travis-ci.org/jacekk/codeception-dataprovider-module/jobs/165395872 - some errors occured on 5.4, but I'll try to play around with that.

**Comment by jacekk** [comment]
@mario-naether 
Improved and released (v1.1.1).
